<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.8" />
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.8" />
		<PackageReference Include="Microsoft.Playwright" Version="1.59.0" />

		<PackageReference Include="Flurl.Http" Version="4.0.2" />
		<PackageReference Include="Telegram.Bot" Version="22.10.0.1" />
		<PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
		
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\libs\DomainDrivenDesign\src\ThabeSoft.DomainDrivenDesign.EntityFrameworkCore\ThabeSoft.DomainDrivenDesign.EntityFrameworkCore.csproj" />
		<ProjectReference Include="..\..\libs\DomainDrivenDesign\src\ThabeSoft.DomainDrivenDesign.Mediator\ThabeSoft.DomainDrivenDesign.Mediator.csproj" />
		<ProjectReference Include="..\..\libs\DomainDrivenDesign\src\ThabeSoft.DomainDrivenDesign\ThabeSoft.DomainDrivenDesign.csproj" />
		<ProjectReference Include="..\..\libs\Mediator\src\ThabeSoft.Mediator.SourceGenerator\ThabeSoft.Mediator.SourceGenerator.csproj"
						  OutputItemType="Analyzer"
						  ReferenceOutputAssembly="false" />
		<ProjectReference Include="..\..\libs\Mediator\src\ThabeSoft.Mediator\ThabeSoft.Mediator.csproj" />
		<ProjectReference Include="..\ImageHub.Abstractions\ImageHub.Abstractions.csproj" />
	</ItemGroup>

</Project>
